server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venturenix_ol?useSSL=false
    username: root
    password: Vin677803

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          import_files: data.sql
    hibernate:
      ddl-auto: update

# App Properties
bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000